### ISSUE TITLE
I thinks, install-store-only.ps1 have 2 bugs.

### ISSUE THREAD

**Issue by kimyoungdu** [Kev403/SurfaceRT-store#1]
Thanks for your script.
I installed Windows 10 on my Surface RT.
I managed to install Windows 10.
But there is no store function.
So I found your script.

Acording to install-store-only.ps1

1) there must be "Microsoft.WindowsStore.appxbundle" file in files diretory.
    But there is no Microsoft.WindowsStore.appxbundle file.

2) I thinks below line miss "\files"
    "Add-AppxPackage $PSScriptRoot\Microsoft.DesktopAppInstaller.AppxBundle"
    -> "Add-AppxPackage $PSScriptRoot\files\Microsoft.DesktopAppInstaller.AppxBundle"

Once again, thanks for your efforts.

**Comment by KeithJackal** [comment]
Thanks for letting me know!

It was a test script I didn't override and accidentally included, it's gone now from next update.
Running the script myself on a fresh installation the error I was getting is this:
![capture1](https://user-images.githubusercontent.com/52633494/122542389-7acf6180-cfdf-11eb-857d-f70c07f94743.png)
Been busy with last few weeks of school so whenever it's done I'm publishing an update!

**Comment by KeithJackal** [comment]
https://drive.google.com/file/d/1hV2EiNnLCA2UONU1UbRS6cnTjwqSIPMA/view?usp=sharing

Issue was the missing package from files, GitHub has 25MB file limit but Store package is 56MB
